#!/bin/sh
# Decommission a cluster member by id
set -e

. ./config

if [ -z "${ID}" ]; then
    echo "usage: stop.sh [1,2,3,4,5]" 1>&2
    exit 1
fi
if [ "${ID}" -gt 5 ] || [ "${ID}" -lt 1 ]; then
    echo "usage: stop.sh [1,2,3,4,5]" 1>&2
    exit 1
fi

if docker run --rm -it --name "rp-stop" \
       --network "${NET}" \
       --entrypoint rpk \
       "${IMAGE}" \
       redpanda admin brokers decommission "${ID}" --force \
       "--hosts=${PREFIX}-1:9644,${PREFIX}-2:9644,${PREFIX}-3:9644" > /dev/null; then
    printf "waiting for %s-%d to decommission" "${PREFIX}" "${ID}"
    while ! docker run --rm -it --name "rp-status" \
           --network "${NET}" \
           --entrypoint rpk \
           "${IMAGE}" \
           redpanda admin brokers decommission-status "${ID}" \
           "--hosts=${PREFIX}-1:9644,${PREFIX}-2:9644,${PREFIX}-3:9644" > /dev/null ; do
        printf "."
        sleep 1
    done
    printf "\n"
else
    echo "failed to decommission ${ID}"
    exit 1
fi

if docker stop "${PREFIX}-${ID}" > /dev/null; then
   echo "stopped ${PREFIX}-${ID}"
fi
