#!/bin/sh
# Stop all brokers
set -e

. ./config

for name in $(docker ps --filter "name=${PREFIX}*" --format '{{.Names}}'); do
    if docker stop "${name}" -t 30 > /dev/null; then
        echo "stopped ${name}"
    fi
done
